google-ID: 'UA-177545877-2'

menu:
  - { name: 'About', url: 'about.html' }
  - { name: 'Archive',  url: 'archive.html' }

social:
  - { icon: 'github',     link: 'https://www.github.com/obround' }
  - { icon: 'envelope',   link: 'mailto:obround.dev@gmail.com' }
  - { icon: 'rss-square', link: '/feed.xml' }

pagination:
  next_page: 'Newer'
  previous_page: 'Older'

related_posts: 'Related Posts:'

post_date_prefix: 'Written on'
